/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class LoadBalancerTest {
    @Test public void appHasAGreeting() {
        LoadBalancer classUnderTest = new LoadBalancer();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
